name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Change this if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Taxi-Booking
            if [ ! -d ".git" ]; then
              echo "Error: Not inside a Git repository!"
              exit 1
            fi
            git pull origin main
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install dependencies
            python manage.py migrate  # Apply database migrations
            python manage.py collectstatic --noinput  # Collect static files
            sudo systemctl restart gunicorn  # Restart backend service
      - name: Deploy Frontend to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: "taxi-booking-fronted"
          AWS_ACCESS_KEY_ID: "ASIA5NPQ6YCDOY72LWQF"
          AWS_SECRET_ACCESS_KEY: "7si/LGtjMDKCSImY9a+mtmRrqnVapZmm+F6ctyAb"
          AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEAkaCXVzLXdlc3QtMiJIMEYCIQDfnHNbQ3qV5CfRfWXQk4KeBz5LR1eLG3lHFGaIuEV0fgIhAOMwTlHV6F9gd9n8eavrGIC1tu2UHDaeOwWDfUxZhuhBKrQCCGEQARoMOTIyMzEyNjg3NzUwIgzj3ivjsgc/rltmtUcqkQJspJR949QD5IZhvBt7aFRmSCzRB811XMjUsSoFSIeglFYu1QMKStE/uXdUSuwmMdpMlDn1Z4kSz8Wz8i7w4azVDvtsORXvUyl3daB5pXcuJbHCijcBPO9gjeMC2kF3+AoSneAgcw13GSLVvop9+7VdgsBCiuDnFp1OMgAEFLVcl43JrCnHKVxAvwoklmQ0rZrzAMt76g7564CTkm3i0vfVF0DFBPNn7xokJr/YiAmp3Z7wV1EAoHeD1gQMZGHyNmJAgyyBlX+JrP5FZoaAj2h+b/GAnd7X/5hT9v3lIKQ5UNVAwhBffrstp/rVdZsZBQV8gkkpnMjJQ8WhBW5PL6GVYg9D1y5msTjucwUHxGv07vgw2LrmvgY6nAHtJsx3gg2E5sFXs480napu6qobAuLAwz8FdoY87ATgTr66Yj1SutrpRVvWCBaw3YNIK5nssFPNO0qw4i6dxG5cKXI2yXLaGmr+Xolzgwy/VK+soml7s+LInCXOaMBY6wE6movn/KE9nONmQbqAKL9qf0SlyERj9UXr04lk3UFndKKk2LB2+gvi89uRoHIjPO4038q5sAtcpc9welU="
          SOURCE_DIR: "frontend"  # Change this to your frontend directory
