name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Change this if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Taxi\Booking
            git pull origin main
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install dependencies
            python manage.py migrate  # Apply database migrations
            python manage.py collectstatic --noinput  # Collect static files
            sudo systemctl restart gunicorn  # Restart backend service
            sudo systemctl restart nginx  # Restart web server
      - name: Deploy Frontend to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: "taxi-booking-fronted"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "frontend"  # Change this to your frontend directory
